version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: vuducdung
      POSTGRES_PASSWORD: 24022003
      POSTGRES_DB: url_shortener
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
